### ISSUE TITLE
Complication content not show in watchOS

### ISSUE THREAD

**Issue by phongdk29101999** [LEOYoon-Tsaw/ChineseTime#2]
Thanks for your project.
I learned many things with it, but I see a problem.
I used watch app in iPhone to set up complication in watch.
But complication content us not shown and it show redacted content.
Anh if i touch in "More" button, watch app is crashed.

![Screenshot 2024-05-07 at 01 14 10](https://github.com/LEOYoon-Tsaw/Chinendar/assets/62046827/04f9ac59-0ddf-4bb9-80ff-0786ae3f5b81)

Simulator:
iPhone 14 Pro (iOS 16.1)
watch Ultra 49mm (watchOS 10.4)

Hope you can check the bug

**Comment by LEOYoon-Tsaw** [comment]
Hi, glad you found it interesting!

But I don't think there's a problem with the complication though, as on my watch it runs perfectly:

![image](https://github.com/LEOYoon-Tsaw/Chinendar/assets/4469383/e788287f-d48e-44f3-87c2-978dec634e23)

You could select the widget as run target, and check in console what error it throughs out

**Comment by kpdo2910** [comment]
Thanks for your reply!
I selected the widget target to run, and no error throughs out in console.
But the complication's error still occurs
P/s: When I select complication in watch or try in another pair, it's ok. May be that is bug of apple watch app.

**Comment by LEOYoon-Tsaw** [comment]
Could be ... there's no problem in real life use
