### ISSUE TITLE
建議推出不受時區影響的「國際漢曆」

### ISSUE THREAD

**Issue by Guest-615695028** [LEOYoon-Tsaw/ChineseTime#3]
本人知悉1985年我國春節相比越南遲一個月，爲推進國際農曆共識建設（中國北京在東八區，朝鮮半島在東八區半，日本在東九區，越南在東七區，中國西藏在東六區），本人特意重新編排漢曆，要求中氣（雨水、春分、穀雨、小滿、夏至、大暑、處暑、秋分、霜降、小雪、冬至、大寒）先於合朔時刻就歸入前一月，以避免時區差異導致分月差異。

## 參考
本人[《農曆問題》](/Guest-615695028/Guest-615695028/blob/main/zh/中華文化復興指南/農曆問題.md)
中國日曆網[《二十四節氣表》](https://www.chinesecalendaronline.com/zh/jieqi)

## 部分結論
|年份|應閏|應新年
|-|-|-
|1985|閏三月|1月21日
|2034|閏正月|1月20日

**Comment by LEOYoon-Tsaw** [comment]
已經包含了，設定置閏「精確至時刻」即爲你說的規則

**Comment by Guest-615695028** [comment]
「已經包含了」？源代碼文件位置？

**Comment by LEOYoon-Tsaw** [comment]
App內選項如下：
![image](https://github.com/user-attachments/assets/cd76f193-7372-4730-92d4-daa6165627d9)

源代碼你搜索「globalMonth」即可

**Comment by Guest-615695028** [comment]
2033年臘八節在12月29日，不入次年，爲最早臘八，而不是1月27日。

**Comment by LEOYoon-Tsaw** [comment]
> 2033年臘八節在12月29日，不入次年。

是的
![image](https://github.com/user-attachments/assets/55a6fc30-5b09-4934-a02a-10b32ae5004a)

**Comment by Guest-615695028** [comment]
> 2033年臘八節在12月29日，不入次年，爲最早臘八，而不是1月27日。

那好，中華人民共和國國務院哪年會在閏五月或六月初五、閏八月或九月十五等前後錯誤放假？類似1985年二月初一（2月20日）、2034年閏正月初一（2月19日）等。

情形一：中氣在朔日但早於合朔時刻。

情形二：出現「雙中氣月」或兩個以上「無中氣月」。

解釋：按具體時區時間（例如上海時間，UTC+8），相鄰兩朔日的零時整（含前不含後，29或30日）之間可能出現兩次中氣（兩中氣的時間間隔最短是29.44日，最長是31.44日；朔望月平均長29.53日）；若「中氣和朔精確到秒」前提下要求兩冬至間第一對相鄰合朔之間無中氣就置閏，可盡力避免之。

**Comment by LEOYoon-Tsaw** [comment]
按照用戶設定的時區以及置閏是否精確至具體時刻，可以計算出1901-2999年間的華曆，符合你說的條件的時刻你可以自己去找，本App不需要提供這種查找功能

**Comment by Guest-615695028** [comment]
> > 2033年臘八節在12月29日，不入次年，爲最早臘八，而不是1月27日。
> 
> 那好，中華人民共和國國務院哪年會在閏五月或六月初五、閏八月或九月十五等前後錯誤放假？類似1985年二月初一（2月20日）、2034年閏正月初一（2月19日）等。
> 
> 情形一：中氣在朔日但早於合朔時刻。
> 
> 情形二：出現「雙中氣月」或兩個以上「無中氣月」。
> 
> 解釋：按具體時區時間（例如上海時間，UTC+8），相鄰兩朔日的零時整（含前不含後，29或30日）之間可能出現兩次中氣（兩中氣的時間間隔最短是29.44日，最長是31.44日；朔望月平均長29.53日）；若「中氣和朔精確到秒」前提下要求兩冬至間第一對相鄰合朔之間無中氣就置閏，可盡力避免之。

就是説，我如果開辦企業，可以在這些情形的年份讓員工多放一次節假。

**Comment by LEOYoon-Tsaw** [comment]
算出合朔時間和中氣時間，for循環跑一遍唄
