### ISSUE TITLE
增加系統支持

### ISSUE THREAD

**Issue by Guest-615695028** [LEOYoon-Tsaw/ChineseTime#4]
據瞭解，編程語言Swift僅支持蘋果公司操作系統，能否以JS代之？希望增加如下系統支持：
Known is it that Swift programming language only supports Apple operating systems, so could you replace it with JavaScript? Expecting support for some operative systems below.
- Linux
- Linux Terminal
- Windows
- Windows Powershell
- Android
- HarmonnyOS

**Comment by LEOYoon-Tsaw** [comment]
我沒有寫過JS，完全不會，如果你有能力的話歡迎port，開源的目的就是希望給有興趣的人能借鑒哈

**Comment by Guest-615695028** [comment]
那麽問題是，有沒有農曆時間表？

**Comment by LEOYoon-Tsaw** [comment]
一週內會增加華曆到格里曆的轉換

**Comment by Guest-615695028** [comment]
我説的是，每個朔和中氣的協調世界時表格。

**Comment by LEOYoon-Tsaw** [comment]
Data.swift中有計算使用的數據，但並不是直接存時間，那樣非常浪費空間

**Comment by Guest-615695028** [comment]
問題是，[這些數據](https://github.com/LEOYoon-Tsaw/Chinendar/blob/main/Shared/DataModel/Data.swift)如何解讀？

**Comment by LEOYoon-Tsaw** [comment]
> 問題是，[這些數據](https://github.com/LEOYoon-Tsaw/Chinendar/blob/main/Shared/DataModel/Data.swift)如何解讀？

相應邏輯在Calendar.swift中

**Comment by Guest-615695028** [comment]
還有，這些數據來源是不是[GB/T 33661-2017](http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=E107EA4DE9725EDF819F33C60A44B296)規定的？「太陽和月球的位置按[國際地球自轉和參考系服務規範規定的模型](https://www.iers.org/IERS/EN/DataProducts/data.html)計算。朔和節氣的北京時間計算精度應達到1秒，不計及編算時尚未正式發佈的閏秒。」即是説，如果兩次合朔之間沒有中氣，就要置閏；如果中氣在朔日但時分秒先於朔，則中氣歸入前一月，同時或後於朔則歸入本月。

華曆到格里曆的轉換上溯到哪一年月日？

**Comment by LEOYoon-Tsaw** [comment]
看代碼吧，太陽系行星位置計算的算法註明了出處。
適用於1901-2999年
